#!/usr/bin/env python3
"""Batch polish Invest Anchors / 定錨產業筆記 ASR transcripts.

This is a conservative terminology/proper-noun correction pass for the
existing timestamped Markdown transcripts under reports/investanchors/.
It does not invent missing content; it only fixes high-confidence ASR
misrecognitions observed across the 13 files.
"""
from __future__ import annotations

from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORT_DIR = ROOT / "reports" / "investanchors"

GENERAL_REPLACEMENTS: dict[str, str] = {
    # Show / host / common words
    "電毛產業筆記": "定錨產業筆記",
    "電話產業筆記": "定錨產業筆記",
    "電毛": "定錨",
    "地毛": "定錨",
    "定毛": "定錨",
    "定謀": "定錨",
    "地牨": "定錨",
    "易正彥": "正彥",
    "政院各位": "正彥、各位",
    "研究人Eric": "研究員 Eric",
    "研究員6": "研究員 Leo",
    "研究員六": "研究員 Leo",
    "我是六": "我是 Leo",
    "我是劉": "我是 Leo",
    "我是Rio": "我是 Leo",
    "Rio": "Leo",
    # NVIDIA / AI server / compute
    "EVIDIA": "NVIDIA",
    "IMIDIRA": "NVIDIA",
    "MVW": "NVIDIA",
    "Kiber Rig": "Kyber Rack",
    "Kyber Rake": "Kyber Rack",
    "開伯": "Kyber",
    "Brufield": "BlueField",
    "Great CPU": "Grace CPU",
    "Gb300": "GB300",
    "Gb200": "GB200",
    "CX9": "ConnectX-9",
    "AIS服務器": "AI 伺服器",
    "AISF系": "AI 伺服器",
    "AISFC": "AI 伺服器",
    "ASFC公率": "AI 伺服器功率",
    "ASFC": "AI 伺服器",
    "AISF器": "AI 伺服器",
    "ASF系": "AI 伺服器",
    "SIFC產品": "AI 伺服器產品",
    "AIS-FG": "AI 伺服器",
    "AI4V7": "AI 伺服器",
    "iS 5 器": "AI 伺服器",
    "S57": "AI 伺服器",
    "服務器": "伺服器",
    "雲端4V7": "雲端伺服器",
    "KVcatch": "KV cache",
    "KVcache": "KV cache",
    "CHAT GPTR": "ChatGPT",
    "Share GPT": "ChatGPT",
    "GEMINALYZ": "Gemini",
    # Taiwan / listed companies / semis
    "台一電": "台積電",
    "洪海": "鴻海",
    "廣大": "廣達",
    "星星電子": "欣興電子",
    "經元店": "京元電",
    "台藥": "台燿",
    "那樣刻": "南亞科",
    "滑包電": "華邦電",
    "旺紅": "旺宏",
    "長新存儲": "長鑫存儲",
    "造業創新": "兆易創新",
    "海利市": "SK 海力士",
    "青州廠": "清州廠",
    "評則廠": "平澤廠",
    "評則長": "平澤廠",
    "凱霞": "鎧俠",
    "inferno": "Infineon",
    "Nespira": "Nexperia",
    "Unsemi": "onsemi",
    "S-Mode": "ASML",
    # Memory / semis
    "低潤": "DRAM",
    "HBN": "HBM",
    "NANDFISH": "NAND Flash",
    "NanFlash": "NAND Flash",
    "NAMFLAGE": "NAND Flash",
    "MLCNanFlash": "MLC NAND Flash",
    "TLCNanFlash": "TLC NAND Flash",
    "Nolflash": "NOR Flash",
    "碳化系": "碳化矽",
    "公率元件": "功率元件",
    "公號": "功耗",
    "滯流電": "直流電",
    "KPEX": "CAPEX",
    "KFX": "CAPEX",
    "Azik": "ASIC",
    "曝光圍影": "曝光微影",
    "TiPro": "tape-out",
    # Advanced packaging / foundry
    "先進風裝": "先進封裝",
    "新進風裝": "先進封裝",
    "先進風段": "先進封裝",
    "風裝測試": "封裝測試",
    "風車廠": "封測廠",
    "風策族群": "封測族群",
    "風測": "封測",
    "風裝": "封裝",
    "法索會": "法說會",
    "法術會": "法說會",
    "法售": "法說會",
    "法收費": "法說會",
    "法收位": "法說會",
    "出發收費": "法說會",
    "發售會": "法說會",
    "法手會": "法說會",
    "法說會會": "法說會",
    "CoAWAS": "CoWoS",
    "CoreWars": "CoWoS",
    "Core Wars": "CoWoS",
    "消耗Core先進封裝": "消耗 CoWoS 先進封裝",
    "台積電Core先進封裝": "台積電 CoWoS 先進封裝",
    "Core先進封裝": "CoWoS 先進封裝",
    "Colors": "CoWoS",
    "Copods": "CoWoS",
    "FleechBump": "Flip-chip bump",
    "Minecraft Bump": "micro bump",
    "尾外": "委外",
    "為外": "委外",
    "亮產": "量產",
    "營收韌理": "營收認列",
    "任列": "認列",
    "抑制整合": "異質整合",
    "深層是AI": "生成式 AI",
    "代理是AI": "代理式 AI",
    "GCC": "GTC",
    "Gin背景賽": "軍備競賽",
    "上援": "上緣",
    "先進製成": "先進製程",
    "之城": "製程",
    "ENIB": "EMIB",
    "每一衝圖": "美伊衝突",
    "黑天的帶來零": "黑天鵝的來臨",
    "封控": "風控",
    "純線股": "純現股",
    "華語權": "話語權",
    "泛緩投資": "放緩投資",
    # Optical / CPO / silicon photonics
    "OSC": "OCS",
    "OFZ": "OFC",
    "CPU交換器": "CPO 交換器",
    "CPU架構": "CPO 架構",
    "把CPU跟OCS": "把 CPO 跟 OCS",
    "CPU跟NPO": "CPO 跟 NPO",
    "NPO或CPU": "NPO 或 CPO",
    "CPU在Scale Up": "CPO 在 Scale Up",
    "走向CPU": "走向 CPO",
    "盧明騰": "Lumentum",
    "Lumanton": "Lumentum",
    "Luminton": "Lumentum",
    "Lumintone": "Lumentum",
    "Luminten": "Lumentum",
    "Lumint or Corridor": "Lumentum 或 Coherent",
    "Lumint和Corridor": "Lumentum 和 Coherent",
    "Lumintum": "Lumentum",
    "LUMENTON": "Lumentum",
    "Fabernet": "Fabrinet",
    "FabriNet": "Fabrinet",
    "Cohirant": "Coherent",
    "Cohiro": "Coherent",
    "COHEERON": "Coherent",
    "Coyron": "Coherent",
    "Corridor": "Coherent",
    "Cohirin": "Coherent",
    "可依人": "Coherent",
    "Cohen": "Coherent",
    "VigCel": "VCSEL",
    "V-cell": "VCSEL",
    "MICOLED": "Micro LED",
    "MICOLENS": "Microlens",
    "EPI WAVER": "EPI wafer",
    "零化銀": "磷化銦",
    "零化英": "磷化銦",
    "零化音機板": "磷化銦基板",
    "零化音雷金": "磷化銦磊晶",
    "零化鷹基板": "磷化銦基板",
    "零化鷹的雷經營廠": "磷化銦的磊晶廠",
    "零化鷹": "磷化銦",
    "零化音": "磷化銦",
    "深化加": "砷化鎵",
    "雷金": "磊晶",
    "細光CW雷射": "矽光 CW 雷射",
    "曦光": "矽光",
    "細光": "矽光",
    "矽光紫": "矽光子",
    "光星數": "光訊號",
    "光線整理": "光纖陣列",
    "多魔光先": "多模光纖",
    "共風狀": "共封裝",
    "細基底": "矽基底",
    "馬費爾": "Marvell",
    "Shufflebox": "Shuffle Box",
    "Single Role": "Single Row",
    "Two Role": "Two Row",
    "Multi Role": "Multi Row",
    "高金蜜": "高精密",
    "金蜜": "精密",
    "光護鏈": "光互聯",
    "護鏈": "互聯",
    "PICTIA": "PIC/TIA",
    "LIFT層": "leaf 層",
    "Spide層": "spine 層",
    "可插法式": "可插拔式",
    "Saki": "socket",
    # PCB / CCL / materials
    "材板": "載板",
    "栽搬": "載板",
    "栽板": "載板",
    "同波機板": "銅箔基板",
    "波鮮布": "玻纖布",
    "波鮮部": "玻纖布",
    "波線部": "玻纖布",
    "播線部": "玻纖布",
    "波線布": "玻纖布",
    "播部": "玻纖布",
    "ROCT玻纖布": "low-CTE 玻纖布",
    "ROCT波鮮布": "low-CTE 玻纖布",
    "拾音布": "石英布",
    "實音布": "石英布",
    "石英部": "石英布",
    "實音部": "石英布",
    "使用部": "石英布",
    "High Lear Count": "High Layer Count",
    "M8CCL": "M8 CCL",
    "Low DK II": "Low Dk II",
    "Low DK2": "Low Dk II",
    "Low DK": "Low Dk",
    "Low CTEEEE": "Low CTE",
    "Low CTEEE": "Low CTE",
    "Low CTEE": "Low CTE",
    "HBL四": "HVLP4",
    "陳數": "層數",
    "10成": "10層",
    "20成": "20層",
    "22成": "22層",
    "26成": "26層",
    "44成": "44層",
    "成版": "層板",
    "孟孔": "盲孔",
    "專真": "鑽針",
    "專孔": "鑽孔",
    "磚孔": "鑽孔",
    "壓核": "壓合",
    "壓額": "壓合",
    "兩率": "良率",
    "真頂": "臻鼎",
    "定義": "定穎",
    "護士店": "滬士電",
    "金像店": "金像電",
    "盛紅": "勝宏",
    "人幣": "人民幣",
    "NITO寶": "Nittobo（日東紡）",
    "Nitobo": "Nittobo（日東紡）",
    "Nidobo": "Nittobo（日東紡）",
    "日容房": "日東紡",
    "CZL廠": "CCL廠",
    "中細台系": "中系、台系",
    "中細": "中系",
    "台戲": "台系",
    "工藝商": "供應商",
    "工業商": "供應商",
    "工區": "供給",
    "工級": "供給",
    "三景金屬": "三井金屬",
    "骨盒電工": "古河電工",
    "通波": "銅箔",
    "受會": "受惠",
    # Passive / power / facilities
    "廠物工程": "廠務工程",
    "廠物": "廠務",
    "廠屋": "廠務",
    "產物": "廠務",
    "大學供應系統": "化學供應系統",
    "無程式與積電": "無塵室與機電",
    "無程式": "無塵室",
    "電容融資": "電容容值",
    "更高融資的電容": "更高容值的電容",
    "高融值": "高容值",
    "低融值": "低容值",
    "基層桃磁電容": "積層陶瓷電容",
    "旅職電容": "鋁質電容",
    "公擠": "供給",
    "被動元件的攻擊": "被動元件的供給",
    "訂單出戶比": "訂單出貨比",
    "日本預算家": "日本被動元件廠商",
    "少年出貨": "少量出貨",
    "收賄": "受惠",
    "固執": "估值",
    # Macro / market
    "領準會": "聯準會",
    "連準會": "聯準會",
    "典准會": "聯準會",
    "Cabin Wash": "Kevin Warsh",
    "Washer": "Warsh",
    "挖旭": "Warsh",
    "大而沒法案": "大而美法案",
    "值利率": "殖利率",
    "日元力差交易": "日圓利差交易",
    "明目利率": "名目利率",
    "貨幣成數": "貨幣乘數",
    "財政策劑": "財政赤字",
    "油資": "游資",
    "克徵": "課徵",
    "寬收環境": "寬鬆環境",
    "不毛而合": "不謀而合",
    "高財生": "高材生",
    "洋行": "央行",
    "主旋率": "主旋律",
    "下雨": "下緣",
    "工藝鏈": "供應鏈",
    "貴數": "櫃數",
    "益起": "預期",
    "貿易烈士": "貿易劣勢",
    "濕橫": "失衡",
    "供聚機": "工具機",
    "水武金": "水五金",
    "SmartX": "Model S",
    "MortelX": "Model X",
    "受信額度": "授信額度",
    "單保": "擔保",
    "半額保人": "擔保人",
    "付美投資": "赴美投資",
    "活領": "獲利",
    "江啟誠": "江啟臣",
    # Defense / drone
    "烏惡戰爭": "烏俄戰爭",
    "烏鱷戰爭": "烏俄戰爭",
    "烏爾戰爭": "烏俄戰爭",
    "高士早苗": "高市早苗",
    "高市早秒": "高市早苗",
    "天空系列": "天弓系列",
    "天空飛彈": "天弓飛彈",
    "天宮": "天弓",
    "天鑒": "天劍",
    "熊峰": "雄風",
    "鐵熊": "鐵穹",
    "精雄系統": "金穹系統",
    "金窮系統": "金穹系統",
    "色頻": "射頻",
    "軟紗": "軟殺",
    "硬紗": "硬殺",
    "金國號": "經國號",
    "零組建": "零組件",
    "軍公展": "軍工展",
    "軍公": "軍工",
    "航胎": "航太",
    "Nachina": "Non-China",
    "工業院": "工研院",
    "資質率": "自製率",
    "仇仔": "酬載",
    "仇宰在": "搭載在",
    "自殺無人艇": "自殺式無人艇",
    "海空號": "海鯤號",
    "駝江艦": "沱江艦",
    "公佈應求": "供不應求",
    "通北季風": "東北季風",
    "對峽": "對峙",
    # Events
    "Competite": "COMPUTEX",
    "computed": "COMPUTEX",
    "touch台灣": "Touch Taiwan",
    "semi-con": "SEMICON",
    "顯示細展": "顯示器展",
    "羅眼": "裸眼",
    "雲車": "暈車",
    "3D運": "3D暈",
}

# Smaller scoped additions by episode title/file name fragment.
SCOPED_REPLACEMENTS: dict[str, dict[str, str]] = {
    "EP5-": {
        "CSPA者": "CSP 業者",
        "消耗CoWoS": "消耗 CoWoS",
        "Io帶": "I/O die",
        "IO-Dyte": "I/O die",
        "精力": "晶粒",
        "頭評量": "投片量",
        "Vanis": "Venice",
    },
    "EP6-": {
        "每股光通訊": "美股光通訊",
        "雷射機片": "雷射晶片",
        "雷射積片": "雷射晶片",
        "矽光子": "矽光子",
        "E-Mail雷射": "EML 雷射",
        "CW雷射": "CW 雷射",
    },
    "EP7-": {
        "公耗": "功耗",
        "融值": "容值",
    },
    "EP8-": {
        "成熟製成": "成熟製程",
        "晶元代工": "晶圓代工",
        "八吋": "8 吋",
        "十二吋": "12 吋",
    },
    "EP9-": {
        "GTC揭露": "GTC 揭露",
        "推論爆發100萬倍": "推論爆發 100 萬倍",
    },
    "EP10-": {
        "CPU 跟 NPO": "CPO 跟 NPO",
        "NPO 或 CPO": "NPO 或 CPO",
    },
    "EP13": {
        "終端CSP": "終端 CSP",
        "中端CSP": "終端 CSP",
        "下游CCL": "下游 CCL",
        "下游PCB": "下游 PCB",
        "CSP廠": "CSP 廠",
        "CCL沒有": "CCL 沒有",
        "PCB的": "PCB 的",
    },
}

NOTE_OLD = "> 注意：本文由 faster-whisper small 自動轉錄，未人工逐字校對；可能仍有斷句或同音字錯誤。"
NOTE_NEW = "> 注意：本文已完成第一輪術語與專有名詞精校；仍保留逐字稿口語與時間戳，引用前建議對照原音檔。"


def apply_replacements(text: str, replacements: dict[str, str], counts: Counter[str]) -> str:
    # Longest first prevents shorter terms from swallowing longer terms.
    for old, new in sorted(replacements.items(), key=lambda kv: len(kv[0]), reverse=True):
        n = text.count(old)
        if n:
            text = text.replace(old, new)
            counts[f"{old} -> {new}"] += n
    return text


def main() -> int:
    files = sorted(REPORT_DIR.glob("*.md"))
    if not files:
        raise SystemExit(f"No markdown files in {REPORT_DIR}")

    total_counts: Counter[str] = Counter()
    touched = 0
    for path in files:
        original = path.read_text(encoding="utf-8")
        counts: Counter[str] = Counter()
        text = original.replace(NOTE_OLD, NOTE_NEW)
        text = apply_replacements(text, GENERAL_REPLACEMENTS, counts)
        for fragment, repl in SCOPED_REPLACEMENTS.items():
            if fragment in path.name:
                text = apply_replacements(text, repl, counts)
        if text != original:
            path.write_text(text, encoding="utf-8")
            touched += 1
            total_counts.update(counts)
            print(f"[polished] {path.name}: {sum(counts.values())} replacements")
            for k, v in counts.most_common(12):
                print(f"  {v:3d}  {k}")
        else:
            print(f"[unchanged] {path.name}")

    print(f"\nTouched files: {touched}/{len(files)}")
    print(f"Total replacements: {sum(total_counts.values())}")
    print("Top replacements:")
    for k, v in total_counts.most_common(40):
        print(f"{v:4d}  {k}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
